//
// Created by ali on 19.10.2022.
//

#ifndef FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP
#define FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP

namespace Fibonacci::Engine::Store {

class IFiboQueryStatisticsStore {


};

}

#endif //FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP
