//
// Created by ali on 20.10.2022.
//

#ifndef FIBONACCI_SERVICE_IFIBOQUERYHISTORYSTORE_HPP
#define FIBONACCI_SERVICE_IFIBOQUERYHISTORYSTORE_HPP

namespace Fibonacci::Engine::Store {

class IFiboQueryHistoryStore {


};

}

#endif //FIBONACCI_SERVICE_IFIBOQUERYHISTORYSTORE_HPP
