//
// Created by ali on 19.10.2022.
//

#ifndef FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP
#define FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP

namespace Fibonacci::Engine::


#endif //FIBONACCI_SERVICE_IFIBOQUERYSTATISTICHOLDER_HPP
