//
// Created by ali on 16.10.2022.
//

#ifndef FIBONACCI_SERVICE_IFIBONACCIENGINELISTENER_HPP
#define FIBONACCI_SERVICE_IFIBONACCIENGINELISTENER_HPP

namespace Fibonacci::Monitor {

class IFibonacciEngineListener {

};

}

#endif //FIBONACCI_SERVICE_IFIBONACCIENGINELISTENER_HPP
