//
// Created by ali on 16.10.2022.
//

#ifndef FIBONACCI_SERVICE_IFIBONACCIENGINEMONITORINGLISTENER_HPP
#define FIBONACCI_SERVICE_IFIBONACCIENGINEMONITORINGLISTENER_HPP

namespace Fibonacci::Monitor {

class IFibonacciEngineMonitoringListener {

};

}

#endif //FIBONACCI_SERVICE_IFIBONACCIENGINEMONITORINGLISTENER_HPP
